export const ARTICLE_ACTIONS = {
  API_GET_ARTICLE_REQUEST: 'API_GET_ARTICLE_REQUEST',
  API_GET_ARTICLE_SUCCESS: 'API_GET_ARTICLE_SUCCESS',
  API_GET_ARTICLE_FAILURE: 'API_GET_ARTICLE_FAILURE',

  API_GET_ARTICLES_REQUEST: 'API_GET_ARTICLES_REQUEST',
  API_GET_ARTICLES_SUCCESS: 'API_GET_ARTICLES_SUCCESS',
  API_GET_ARTICLES_FAILURE: 'API_GET_ARTICLES_FAILURE',

  API_DELETE_ARTICLES_REQUEST: 'API_DELETE_ARTICLES_REQUEST',
  API_DELETE_ARTICLES_SUCCESS: 'API_DELETE_ARTICLES_SUCCESS',
  API_DELETE_ARTICLES_FAILURE: 'API_DELETE_ARTICLES_FAILURE',


  API_CREATE_ARTICLE_REQUEST: 'API_CREATE_ARTICLE_REQUEST',
  API_CREATE_ARTICLE_SUCCESS: 'API_CREATE_ARTICLE_SUCCESS',
  API_CREATE_ARTICLE_FAILURE: 'API_CREATE_ARTICLE_FAILURE',

  API_UPDATE_ARTICLE_REQUEST: 'API_UPDATE_ARTICLE_REQUEST',
  API_UPDATE_ARTICLE_SUCCESS: 'API_UPDATE_ARTICLE_SUCCESS',
  API_UPDATE_ARTICLE_FAILURE: 'API_UPDATE_ARTICLE_FAILURE',

  API_GET_FILTERS_REQUEST: 'API_GET_FILTERS_REQUEST',
  API_GET_FILTERS_SUCCESS: 'API_GET_FILTERS_SUCCESS',
  API_GET_FILTERS_FAILURE: 'API_GET_FILTERS_FAILURE'
}
export const selectArticle = articleId => ({
  type: ARTICLE_ACTIONS.API_GET_ARTICLE_REQUEST,
  articleId
})
export const fetchAvailableFilters = articleId => ({
  type: ARTICLE_ACTIONS.API_GET_FILTERS_REQUEST
})

export const fetchArticles = (filters) => ({
  type: ARTICLE_ACTIONS.API_GET_ARTICLES_REQUEST,
  filters
})


export const createArticle = article => ({
  type: ARTICLE_ACTIONS.API_CREATE_ARTICLE_REQUEST,
  article
})

export const updateArticle = article => ({
  type: ARTICLE_ACTIONS.API_UPDATE_ARTICLE_REQUEST,
  article
})

export const deleteArticles = articleIds => ({
  type: ARTICLE_ACTIONS.API_DELETE_ARTICLES_REQUEST,
  articleIds
})