export const ARTICLE_ACTIONS = {
  API_GET_ARTICLE_REQUEST: 'API_GET_ARTICLE_REQUEST',
  API_GET_ARTICLE_SUCCESS: 'API_GET_ARTICLE_SUCCESS',
  API_GET_ARTICLE_FAILURE: 'API_GET_ARTICLE_FAIULRE',

  API_GET_ARTICLES_REQUEST: 'API_GET_ARTICLES_REQUEST',
  API_GET_ARTICLES_SUCCESS: 'API_GET_ARTICLES_SUCCESS',
  API_GET_ARTICLES_FAILURE: 'API_GET_ARTICLES_FAIULRE'
}
export const selectArticle = articleId => ({
  type: ARTICLE_ACTIONS.API_GET_ARTICLE_REQUEST,
  articleId
})

export const fetchArticles = () => ({
  type: ARTICLE_ACTIONS.API_GET_ARTICLES_REQUEST
})